version: '3.9'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports: ["5435:5432"]
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "max_replication_slots=10"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_sub:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports: ["5436:5432"]
    depends_on: [postgres]
    volumes:
      - postgres_sub_data:/var/lib/postgresql/data

  pgbackups:
    image: bash
    volumes:
      - ./backup.sh:/backup.sh
      - ./dumps:/dumps
    depends_on:
      - postgres
    entrypoint: [ "bash", "-lc", "while true; do /backup.sh; sleep 86400; done" ]

  mongodb:
    image: mongo:6
    container_name: library_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: library
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
  postgres_sub_data:
